<?php return array (
  'application_title' => 'e-shop',
  'site_address' => 'Mirpur 13, Dhaka.',
  'site_phone' => '01770583679',
  'site_email' => 'sarwarhossain.cmt@gmail.com',
  'facebook_link' => 'https://www.facebook.com/pages/#',
  'twitter_link' => 'https://www.twitter.com/pages/#',
  'youtube_link' => 'https://www.youtube.com/pages/#',
  'instagram_link' => 'https://www.instagram.com/pages/#',
  'important_link_1' => '#',
  'important_link_1_name' => 'Quick Delivery.',
  'important_link_2' => '#',
  'important_link_2_name' => 'Good Product.',
  'important_link_3' => '#',
  'important_link_3_name' => 'Safe Payment.',
);